
# 📚 Guía didáctica de **Pandas** — Funciones con ejemplos

Este cuaderno cubre, de forma **didáctica**, todas las funciones que pediste. Cada bloque incluye:
- **Qué hace** la función y **cuándo usarla**
- Un **dataset de ejemplo** (realista y reproducible)
- Un **ejemplo ejecutable** con su salida

> Sugerencia: Ejecuta las celdas **en orden**. Si algo no aparece, revisa que hayas creado los datasets del bloque.

In [1]:

import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 120)

np.random.seed(42)  # Reproducible
print("✅ Entorno listo. Versiones:", "pandas", pd.__version__, "| numpy", np.__version__)

✅ Entorno listo. Versiones: pandas 2.2.3 | numpy 2.0.2


## 🧰 Datasets de ejemplo (base)
Creamos diferentes datasets para reutilizar en varios bloques:
- `empleados`: personas con edad, salario, ciudad y experiencia
- `ventas`: ventas por producto y fecha
- `texto_df`: emails, nombres y comentarios

In [2]:

empleados = pd.DataFrame({
    "id": range(1, 11),
    "nombre": ["Ana","Juan","María","Pedro","Laura","Carlos","Sofía","Miguel","Lucía","Diego"],
    "edad": [25,30,28,35,22,40,27,33,29,31],
    "salario": [30000,45000,38000,52000,28000,60000,35000,48000,41000,39000],
    "ciudad": ["Madrid","Barcelona","Madrid","Valencia","Barcelona","Madrid","Valencia","Barcelona","Sevilla","Sevilla"],
    "experiencia": [2,8,5,12,1,15,4,10,6,7]
})
empleados

   id  nombre  edad  salario     ciudad  experiencia
0   1     Ana    25    30000     Madrid            2
1   2    Juan    30    45000  Barcelona            8
2   3   María    28    38000     Madrid            5
3   4   Pedro    35    52000   Valencia           12
4   5   Laura    22    28000  Barcelona            1
5   6  Carlos    40    60000     Madrid           15
6   7   Sofía    27    35000   Valencia            4
7   8  Miguel    33    48000  Barcelona           10
8   9   Lucía    29    41000    Sevilla            6
9  10   Diego    31    39000    Sevilla            7

In [3]:

fechas = pd.date_range("2024-01-01", periods=12, freq="M")
ventas = pd.DataFrame({
    "fecha": np.repeat(fechas, 3),
    "producto": ["A","B","C"] * len(fechas),
    "unidades": np.random.randint(5, 50, size=len(fechas)*3),
    "precio_unitario": np.random.choice([9.99, 14.99, 19.99], size=len(fechas)*3)
})
ventas["importe"] = ventas["unidades"] * ventas["precio_unitario"]
ventas.head()

C:\Users\User\AppData\Local\Temp\ipykernel_51296\3623486878.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fechas = pd.date_range("2024-01-01", periods=12, freq="M")

       fecha producto  unidades  precio_unitario  importe
0 2024-01-31        A        43             9.99   429.57
1 2024-01-31        B        33            19.99   659.67
2 2024-01-31        C        19            19.99   379.81
3 2024-02-29        A        47             9.99   469.53
4 2024-02-29        B        12             9.99   119.88

In [4]:

texto_df = pd.DataFrame({
    "email": ["ana@gmail.com", "JUAN@hotmail.com", "maria@yahoo.es", "pedro@gmail.com", " laura@empresa.com "],
    "nombre_completo": ["Ana García López", "Juan Pérez", "María Rodríguez", "Pedro Sánchez Martín", "Laura Gómez"],
    "comentario": ["Excelente servicio!", "Muy bueno", "Regular", "Podría mejorar", "  Atención correcta  "]
})
texto_df

                 email       nombre_completo             comentario
0        ana@gmail.com      Ana García López    Excelente servicio!
1     JUAN@hotmail.com            Juan Pérez              Muy bueno
2       maria@yahoo.es       María Rodríguez                Regular
3      pedro@gmail.com  Pedro Sánchez Martín         Podría mejorar
4   laura@empresa.com            Laura Gómez    Atención correcta

---

## 📊 Funciones Estadísticas


Estas funciones sirven para **describir** los datos numéricos: valores extremos, tendencia central, dispersión y acumulados.
Usaremos `empleados` y algunas columnas de `ventas`.

In [5]:

# max / min: extremos
print("max() salario:", empleados["salario"].max())
print("min() salario:", empleados["salario"].min())

# mean / median: tendencia central
print("mean() salario:", empleados["salario"].mean())
print("median() salario:", empleados["salario"].median())

# std / var: dispersión
print("std() salario:", round(empleados["salario"].std(),2))
print("var() salario:", round(empleados["salario"].var(),2))

# sum: totales
print("sum() experiencia total:", empleados["experiencia"].sum())

# quantile: percentiles
print("quantile 25% salario:", empleados["salario"].quantile(0.25))
print("quantile 75% salario:", empleados["salario"].quantile(0.75))

# describe: resumen integral
empleados[["edad","salario","experiencia"]].describe()

max() salario: 60000
min() salario: 28000
mean() salario: 41600.0
median() salario: 40000.0
std() salario: 9901.74
var() salario: 98044444.44
sum() experiencia total: 70
quantile 25% salario: 35750.0
quantile 75% salario: 47250.0

            edad       salario  experiencia
count  10.000000     10.000000    10.000000
mean   30.000000  41600.000000     7.000000
std     5.142416   9901.739466     4.396969
min    22.000000  28000.000000     1.000000
25%    27.250000  35750.000000     4.250000
50%    29.500000  40000.000000     6.500000
75%    32.500000  47250.000000     9.500000
max    40.000000  60000.000000    15.000000

In [ ]:

# cumsum / cumprod / cummax / cummin: acumulados ordenados por id
serie = empleados.sort_values("id")["salario"]
demo = pd.DataFrame({
    "salario": serie,
    "cumsum": serie.cumsum(),
    "cumprod(escala)": (serie/1000).cumprod().round(3),
    "cummax": serie.cummax(),
    "cummin": serie.cummin()
})
demo

In [6]:

# corr / cov: relación lineal entre variables
empleados[["edad","salario","experiencia"]].corr()

                 edad   salario  experiencia
edad         1.000000  0.975408     0.987718
salario      0.975408  1.000000     0.992755
experiencia  0.987718  0.992755     1.000000

In [ ]:

empleados[["edad","salario","experiencia"]].cov()

---

## 🔢 Funciones de Conteo


Sirven para **contar** elementos, frecuencias y cardinalidades.

In [7]:

# count: no cuenta NaN
empleados["edad"].count(), empleados.count()

(np.int64(10),
 id             10
 nombre         10
 edad           10
 salario        10
 ciudad         10
 experiencia    10
 dtype: int64)

In [8]:

# size: número total de elementos (incluye NaN)
empleados["edad"].size, empleados.size

(10, 60)

In [9]:

# len: número de filas
len(empleados)

10

In [10]:

# value_counts: frecuencia de valores
empleados["ciudad"].value_counts(), empleados["ciudad"].value_counts(normalize=True)

(ciudad
 Madrid       3
 Barcelona    3
 Valencia     2
 Sevilla      2
 Name: count, dtype: int64,
 ciudad
 Madrid       0.3
 Barcelona    0.3
 Valencia     0.2
 Sevilla      0.2
 Name: proportion, dtype: float64)

In [11]:

# nunique / unique: cardinalidad y valores únicos
empleados["ciudad"].nunique(), empleados["ciudad"].unique()

(4, array(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'], dtype=object))

---

## 🔍 Selección y Filtrado


Accedemos a filas/columnas y filtramos por condiciones.

In [ ]:

# head / tail / sample
#sample(n) - Devuelve una muestra aleatoria de filas.
empleados.head(3), empleados.tail(2), empleados.sample(3, random_state=0)

(   id nombre  edad  salario     ciudad  experiencia
 0   1    Ana    25    30000     Madrid            2
 1   2   Juan    30    45000  Barcelona            8
 2   3  María    28    38000     Madrid            5,
    id nombre  edad  salario   ciudad  experiencia
 8   9  Lucía    29    41000  Sevilla            6
 9  10  Diego    31    39000  Sevilla            7,
    id nombre  edad  salario     ciudad  experiencia
 2   3  María    28    38000     Madrid            5
 8   9  Lucía    29    41000    Sevilla            6
 4   5  Laura    22    28000  Barcelona            1)

In [13]:

# loc: por etiquetas (índice/columnas)
empleados.loc[0:2, ["nombre","edad","salario"]]

  nombre  edad  salario
0    Ana    25    30000
1   Juan    30    45000
2  María    28    38000

In [14]:

# iloc: por posiciones numéricas
empleados.iloc[0:3, 0:3]

   id nombre  edad
0   1    Ana    25
1   2   Juan    30
2   3  María    28

In [15]:

# query: expresivo y legible
empleados.query("edad > 30 and salario > 40000")

   id  nombre  edad  salario     ciudad  experiencia
3   4   Pedro    35    52000   Valencia           12
5   6  Carlos    40    60000     Madrid           15
7   8  Miguel    33    48000  Barcelona           10

In [16]:

# isin: pertenencia a lista
empleados[empleados["ciudad"].isin(["Madrid","Barcelona"])]

   id  nombre  edad  salario     ciudad  experiencia
0   1     Ana    25    30000     Madrid            2
1   2    Juan    30    45000  Barcelona            8
2   3   María    28    38000     Madrid            5
4   5   Laura    22    28000  Barcelona            1
5   6  Carlos    40    60000     Madrid           15
7   8  Miguel    33    48000  Barcelona           10

In [31]:

# # between: rangos cerrados (incluye extremos)
empleados[empleados["edad"].between(25, 30)]

   id nombre  edad  salario     ciudad  experiencia
0   1    Ana    25    30000     Madrid            2
1   2   Juan    30    45000  Barcelona            8
2   3  María    28    38000     Madrid            5
6   7  Sofía    27    35000   Valencia            4
8   9  Lucía    29    41000    Sevilla            6

In [ ]:

# nlargest / nsmallest: top N por columna
#nlargest(n, col) -	Devuelve las n filas con valores más grandes.
#nsmallest(n, col) - Devuelve las n filas con valores más pequeños.
empleados.nlargest(3, "salario")[["nombre","salario"]], empleados.nsmallest(3, "salario")[["nombre","salario"]]

(   nombre  salario
 5  Carlos    60000
 3   Pedro    52000
 7  Miguel    48000,
   nombre  salario
 4  Laura    28000
 0    Ana    30000
 6  Sofía    35000)

In [19]:

# idxmax / idxmin: posición del extremo (útil para localizar fila completa)
imax = empleados["salario"].idxmax()
imin = empleados["salario"].idxmin()
empleados.loc[[imax, imin], ["nombre","salario","ciudad"]]

   nombre  salario     ciudad
5  Carlos    60000     Madrid
4   Laura    28000  Barcelona

---

## 📝 Funciones de Texto


Operan sobre columnas de tipo `string` vía `.str`. Muy útiles en limpieza y extracción.

In [ ]:

# lower / upper
#str.lower()-Convierte todo el texto a minúsculas.
#str.upper()-Convierte todo el texto a mayúsculas.
texto_df.assign(lower=texto_df["email"].str.lower(), upper=texto_df["nombre_completo"].str.upper())

                 email       nombre_completo             comentario                lower                 upper
0        ana@gmail.com      Ana García López    Excelente servicio!        ana@gmail.com      ANA GARCÍA LÓPEZ
1     JUAN@hotmail.com            Juan Pérez              Muy bueno     juan@hotmail.com            JUAN PÉREZ
2       maria@yahoo.es       María Rodríguez                Regular       maria@yahoo.es       MARÍA RODRÍGUEZ
3      pedro@gmail.com  Pedro Sánchez Martín         Podría mejorar      pedro@gmail.com  PEDRO SÁNCHEZ MARTÍN
4   laura@empresa.com            Laura Gómez    Atención correcta     laura@empresa.com            LAURA GÓMEZ

In [22]:

# contains (con case-insensitive)
texto_df[texto_df["email"].str.contains("gmail")]

             email       nombre_completo           comentario
0    ana@gmail.com      Ana García López  Excelente servicio!
3  pedro@gmail.com  Pedro Sánchez Martín       Podría mejorar

In [23]:

# startswith / endswith
texto_df[texto_df["nombre_completo"].str.startswith("M")], texto_df[texto_df["email"].str.endswith(".com")]

(            email  nombre_completo comentario
 2  maria@yahoo.es  María Rodríguez    Regular,
               email       nombre_completo           comentario
 0     ana@gmail.com      Ana García López  Excelente servicio!
 1  JUAN@hotmail.com            Juan Pérez            Muy bueno
 3   pedro@gmail.com  Pedro Sánchez Martín       Podría mejorar)

In [24]:

# len
texto_df["nombre_completo"].str.len()

0    16
1    10
2    15
3    20
4    11
Name: nombre_completo, dtype: int64

In [25]:

# split en 2 columnas: usuario y dominio bruto
texto_df["email"].str.strip().str.split("@", expand=True).rename(columns={0:"usuario",1:"dominio"})

  usuario      dominio
0     ana    gmail.com
1    JUAN  hotmail.com
2   maria     yahoo.es
3   pedro    gmail.com
4   laura  empresa.com

In [ ]:

# replace: normalizar opiniones
# regex = false , busca exactamente “bueno”, sin interpretar símbolos especiales como . o *
texto_df
texto_df["comentario"].str.replace("bueno","excelente", regex=False)

0      Excelente servicio!
1            Muy excelente
2                  Regular
3           Podría mejorar
4      Atención correcta
Name: comentario, dtype: object

In [39]:

# strip: quitar espacios a izquierda y derecha
texto_df["email"].str.strip()

0        ana@gmail.com
1     JUAN@hotmail.com
2       maria@yahoo.es
3      pedro@gmail.com
4    laura@empresa.com
Name: email, dtype: object

In [40]:

# extract: extraer dominio base (palabras minúsculas hasta el punto)
texto_df["email"].str.strip().str.extract(r"@([a-z]+)\.", expand=False)

0      gmail
1    hotmail
2      yahoo
3      gmail
4    empresa
Name: email, dtype: object

---

## 📊 Agregación y Agrupación

In [41]:

# groupby + mean
empleados.groupby("ciudad")["salario"].mean().round(2)

ciudad
Barcelona    40333.33
Madrid       42666.67
Sevilla      40000.00
Valencia     43500.00
Name: salario, dtype: float64

In [42]:

# agg con varias funciones
empleados.groupby("ciudad")["salario"].agg(["mean","min","max","count"]).round(2)

               mean    min    max  count
ciudad
Barcelona  40333.33  28000  48000      3
Madrid     42666.67  30000  60000      3
Sevilla    40000.00  39000  41000      2
Valencia   43500.00  35000  52000      2

In [43]:

# pivot_table: por defecto agrupa con mean
pd.pivot_table(ventas, values="importe", index="producto", columns=ventas["fecha"].dt.year, aggfunc=["mean","count"]).round(2)

            mean count
fecha       2024  2024
producto
A         497.15    12
B         426.39    12
C         336.02    12

In [ ]:

# crosstab: frecuencias cruzadas
#crosstab() - Crea una tabla de frecuencias cruzadas (filas vs columnas).
empleados["rango_edad"] = pd.cut(empleados["edad"], bins=[0, 30, 40, 100], labels=["Joven","Adulto","Mayor"])
pd.crosstab(empleados["ciudad"], empleados["rango_edad"])

rango_edad  Joven  Adulto
ciudad
Barcelona       2       1
Madrid          2       1
Sevilla         1       1
Valencia        1       1

---

## 🔄 Ordenamiento

In [45]:

# sort_values por una columna
empleados.sort_values("salario", ascending=False)[["nombre","salario"]]

   nombre  salario
5  Carlos    60000
3   Pedro    52000
7  Miguel    48000
1    Juan    45000
8   Lucía    41000
9   Diego    39000
2   María    38000
6   Sofía    35000
0     Ana    30000
4   Laura    28000

In [46]:

# sort_index (útil tras mezclas)
des = empleados.sample(frac=1, random_state=1)
des.sort_index().head()

   id nombre  edad  salario     ciudad  experiencia rango_edad
0   1    Ana    25    30000     Madrid            2      Joven
1   2   Juan    30    45000  Barcelona            8      Joven
2   3  María    28    38000     Madrid            5      Joven
3   4  Pedro    35    52000   Valencia           12     Adulto
4   5  Laura    22    28000  Barcelona            1      Joven

In [ ]:

# rank: ranking (1 = mayor salario si ascending=False)
empleados.assign(ranking_salario=empleados["salario"].rank(ascending=False)).sort_values("ranking_salario").head()

---

## 🧹 Limpieza de Datos

In [ ]:

sucio = pd.DataFrame({
    "A": [1, 2, np.nan, 4, 5, 5, 6],
    "B": [np.nan, 2, 3, 3, np.nan, 6, 7],
    "C": ["a", "b", "c", "c", "d", "d", "e"],
    "D": [10, 20, 30, 40, 50, 60, 70]
})
sucio

In [ ]:

# isna / notna
sucio.isna(), sucio.notna()

In [ ]:

# dropna: eliminar filas con nulos; o columnas con nulos
sucio.dropna(), sucio.dropna(axis=1)

In [ ]:

# fillna: varios métodos
sucio.fillna(0), sucio.fillna(sucio.mean(numeric_only=True)), sucio.fillna(method="ffill")

In [ ]:

# drop_duplicates / duplicated
sucio.drop_duplicates(subset=["A"]), sucio.duplicated(subset=["C"]), sucio[sucio.duplicated(subset=["C"], keep=False)]

In [ ]:

# replace: mapeos simples o múltiples
sucio["C"].replace({"a":"A","b":"B"}), sucio.replace([1,2],[100,200])

In [ ]:

# interpolate: estimar valores en serie numérica
serie = pd.Series([1, np.nan, np.nan, 4, 5, np.nan, 7])
serie, serie.interpolate()

---

## 🔧 Transformación

In [ ]:

# apply: columna derivada
empleados.assign(salario_mensual = empleados["salario"] / 12).head()

In [ ]:

# map: a partir de diccionario
regiones = {"Madrid":"Centro", "Barcelona":"Noreste", "Valencia":"Este", "Sevilla":"Sur"}
empleados.assign(region = empleados["ciudad"].map(regiones)).head()

In [ ]:

# astype: conversión de tipos
empleados.assign(edad_float = empleados["edad"].astype(float)).dtypes

In [ ]:

# cut: categorizar por rangos
empleados.assign(cat_salario = pd.cut(empleados["salario"], bins=[0,35000,45000,1e6], labels=["Bajo","Medio","Alto"]))[[ "nombre","salario","cat_salario"]]

In [ ]:

# qcut: categorizar por cuantiles (mismo nº de elementos por grupo)
empleados.assign(q_salario = pd.qcut(empleados["salario"], q=4, labels=["Q1","Q2","Q3","Q4"]))[[ "nombre","salario","q_salario"]]

In [ ]:

# rename: renombrar columnas
empleados.rename(columns={"nombre":"name","edad":"age","ciudad":"city"}).head(2)

In [ ]:

# reset_index / set_index / transpose
tmp = empleados[empleados["edad"]>30]
tmp_before = tmp.index
tmp_after = tmp.reset_index(drop=True).index
(
    tmp_before.tolist(), tmp_after.tolist(),
    empleados.set_index("nombre").head(2),
    empleados[["nombre","edad","salario"]].head(3).T
)

---

## 🔗 Combinación de DataFrames

In [26]:

left = pd.DataFrame({"id":[1,2,3,4],"nombre":["Ana","Juan","María","Pedro"],"edad":[25,30,28,35]})
right = pd.DataFrame({"id":[2,3,4,5],"ciudad":["Barcelona","Madrid","Valencia","Sevilla"],"salario":[45000,38000,52000,40000]})
left, right

(   id nombre  edad
 0   1    Ana    25
 1   2   Juan    30
 2   3  María    28
 3   4  Pedro    35,
    id     ciudad  salario
 0   2  Barcelona    45000
 1   3     Madrid    38000
 2   4   Valencia    52000
 3   5    Sevilla    40000)

In [27]:

# merge: inner, left, outer
pd.merge(left, right, on="id", how="inner"), pd.merge(left, right, on="id", how="left"), pd.merge(left, right, on="id", how="outer")

(   id nombre  edad     ciudad  salario
 0   2   Juan    30  Barcelona    45000
 1   3  María    28     Madrid    38000
 2   4  Pedro    35   Valencia    52000,
    id nombre  edad     ciudad  salario
 0   1    Ana    25        NaN      NaN
 1   2   Juan    30  Barcelona  45000.0
 2   3  María    28     Madrid  38000.0
 3   4  Pedro    35   Valencia  52000.0,
    id nombre  edad     ciudad  salario
 0   1    Ana  25.0        NaN      NaN
 1   2   Juan  30.0  Barcelona  45000.0
 2   3  María  28.0     Madrid  38000.0
 3   4  Pedro  35.0   Valencia  52000.0
 4   5    NaN   NaN    Sevilla  40000.0)

In [ ]:

# concat: vertical y horizontal
a = pd.DataFrame({"A":[1,2], "B":[3,4]})
b = pd.DataFrame({"A":[5,6], "B":[7,8]})
pd.concat([a,b], ignore_index=True), pd.concat([a,b], axis=1)

(   A  B
 0  1  3
 1  2  4
 2  5  7
 3  6  8,
    A  B
 0  1  3
 1  2  4
 0  5  7
 1  6  8)

In [ ]:

# join: por índice
l = pd.DataFrame({"A":[1,2,3]}, index=["a","b","c"])
r = pd.DataFrame({"B":[4,5,6]}, index=["b","c","d"])
l.join(r, how="outer")

In [ ]:

# append: hoy se recomienda usar concat (append está deprecado)
base = pd.DataFrame({"nombre":["Ana"],"edad":[25]})
nueva = pd.DataFrame({"nombre":["Lucía"],"edad":[26]})
pd.concat([base, nueva], ignore_index=True)

---

## 📋 Funciones de Información

In [ ]:

# info: resumen del DF
empleados.info()

In [ ]:

# shape / columns / dtypes
empleados.shape, list(empleados.columns), empleados.dtypes

In [ ]:

# memory_usage / select_dtypes
empleados.memory_usage(deep=True), empleados.select_dtypes(include=["int64","float64"]).head(2), empleados.select_dtypes(include=["object"]).head(2)

---

## 🎯 Funciones Adicionales Útiles

In [ ]:

# copy: copia independiente
copia = empleados.copy()
copia.loc[0, "edad"] = 999
empleados.loc[0, "edad"], copia.loc[0, "edad"]

In [ ]:

# drop: eliminar columnas y filas
empleados.drop(columns=["experiencia"]).head(2), empleados.drop(index=[0,1]).head(2)

In [ ]:

# clip: limitar valores a un rango
empleados.assign(salario_clip = empleados["salario"].clip(30000, 50000))[["nombre","salario","salario_clip"]].head()

In [ ]:

# where / mask
empleados.assign(salario_where = empleados["salario"].where(empleados["salario"]>40000)).head(), empleados.assign(salario_mask = empleados["salario"].mask(empleados["salario"]>40000, "ALTO")).head()

In [ ]:

# abs: valor absoluto | round: redondeo
neg = pd.DataFrame({"valores":[-5,-3,2,8,-1]})
neg.assign(abs=neg["valores"].abs()), empleados.assign(salario_miles = empleados["salario"].round(-3)).head()

In [ ]:

# to_dict / to_csv (solo mostramos la sintaxis, no escribimos archivo aquí)
empleados.head(3).to_dict("records")
# Para exportar: empleados.to_csv("empleados.csv", index=False, encoding="utf-8")


---

**Fin del cuaderno.**